# pyproject.toml

# pytest configuration
[tool.pytest.ini_options]
pythonpath = [
    #  The directory where source code locates
    "libsys"
]

## pylint configuration
[tool.pylint]
# Disable checkers
disable = [
    #  Disable Import-Error checker to skip the check of importing local modules
    "import-error",
    "unused-import"
]